/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.14.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientVariantSchemaPayload
 */
export interface ClientVariantSchemaPayload {
    /**
     * 
     * @type {string}
     * @memberof ClientVariantSchemaPayload
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ClientVariantSchemaPayload
     */
    value: string;
}

/**
 * Check if a given object implements the ClientVariantSchemaPayload interface.
 */
export function instanceOfClientVariantSchemaPayload(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function ClientVariantSchemaPayloadFromJSON(json: any): ClientVariantSchemaPayload {
    return ClientVariantSchemaPayloadFromJSONTyped(json, false);
}

export function ClientVariantSchemaPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientVariantSchemaPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
    };
}

export function ClientVariantSchemaPayloadToJSON(value?: ClientVariantSchemaPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'value': value.value,
    };
}

