/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.14.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClientVariantSchemaPayload } from './ClientVariantSchemaPayload';
import {
    ClientVariantSchemaPayloadFromJSON,
    ClientVariantSchemaPayloadFromJSONTyped,
    ClientVariantSchemaPayloadToJSON,
} from './ClientVariantSchemaPayload';

/**
 * 
 * @export
 * @interface ClientVariantSchema
 */
export interface ClientVariantSchema {
    /**
     * 
     * @type {string}
     * @memberof ClientVariantSchema
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ClientVariantSchema
     */
    weight: number;
    /**
     * 
     * @type {ClientVariantSchemaPayload}
     * @memberof ClientVariantSchema
     */
    payload?: ClientVariantSchemaPayload;
}

/**
 * Check if a given object implements the ClientVariantSchema interface.
 */
export function instanceOfClientVariantSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "weight" in value;

    return isInstance;
}

export function ClientVariantSchemaFromJSON(json: any): ClientVariantSchema {
    return ClientVariantSchemaFromJSONTyped(json, false);
}

export function ClientVariantSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientVariantSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'weight': json['weight'],
        'payload': !exists(json, 'payload') ? undefined : ClientVariantSchemaPayloadFromJSON(json['payload']),
    };
}

export function ClientVariantSchemaToJSON(value?: ClientVariantSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'weight': value.weight,
        'payload': ClientVariantSchemaPayloadToJSON(value.payload),
    };
}

