/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.14.0-beta.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PlaygroundFeatureSchemaVariantPayload
 */
export interface PlaygroundFeatureSchemaVariantPayload {
    /**
     *
     * @type {string}
     * @memberof PlaygroundFeatureSchemaVariantPayload
     */
    type: PlaygroundFeatureSchemaVariantPayloadTypeEnum;
    /**
     *
     * @type {string}
     * @memberof PlaygroundFeatureSchemaVariantPayload
     */
    value: string;
}


/**
 * @export
 */
export const PlaygroundFeatureSchemaVariantPayloadTypeEnum = {
    Json: 'json',
    Csv: 'csv',
    String: 'string'
} as const;
export type PlaygroundFeatureSchemaVariantPayloadTypeEnum = typeof PlaygroundFeatureSchemaVariantPayloadTypeEnum[keyof typeof PlaygroundFeatureSchemaVariantPayloadTypeEnum];


/**
 * Check if a given object implements the PlaygroundFeatureSchemaVariantPayload interface.
 */
export function instanceOfPlaygroundFeatureSchemaVariantPayload(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function PlaygroundFeatureSchemaVariantPayloadFromJSON(json: any): PlaygroundFeatureSchemaVariantPayload {
    return PlaygroundFeatureSchemaVariantPayloadFromJSONTyped(json, false);
}

export function PlaygroundFeatureSchemaVariantPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaygroundFeatureSchemaVariantPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'type': json['type'],
        'value': json['value'],
    };
}

export function PlaygroundFeatureSchemaVariantPayloadToJSON(value?: PlaygroundFeatureSchemaVariantPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'type': value.type,
        'value': value.value,
    };
}

