/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.14.0-beta.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlaygroundFeatureSchemaVariantPayload } from './PlaygroundFeatureSchemaVariantPayload';
import {
    PlaygroundFeatureSchemaVariantPayloadFromJSON,
    PlaygroundFeatureSchemaVariantPayloadFromJSONTyped,
    PlaygroundFeatureSchemaVariantPayloadToJSON,
} from './PlaygroundFeatureSchemaVariantPayload';

/**
 * 
 * @export
 * @interface PlaygroundFeatureSchemaVariant
 */
export interface PlaygroundFeatureSchemaVariant {
    /**
     * 
     * @type {string}
     * @memberof PlaygroundFeatureSchemaVariant
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlaygroundFeatureSchemaVariant
     */
    enabled: boolean;
    /**
     * 
     * @type {PlaygroundFeatureSchemaVariantPayload}
     * @memberof PlaygroundFeatureSchemaVariant
     */
    payload?: PlaygroundFeatureSchemaVariantPayload;
}

/**
 * Check if a given object implements the PlaygroundFeatureSchemaVariant interface.
 */
export function instanceOfPlaygroundFeatureSchemaVariant(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "enabled" in value;

    return isInstance;
}

export function PlaygroundFeatureSchemaVariantFromJSON(json: any): PlaygroundFeatureSchemaVariant {
    return PlaygroundFeatureSchemaVariantFromJSONTyped(json, false);
}

export function PlaygroundFeatureSchemaVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaygroundFeatureSchemaVariant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'enabled': json['enabled'],
        'payload': !exists(json, 'payload') ? undefined : PlaygroundFeatureSchemaVariantPayloadFromJSON(json['payload']),
    };
}

export function PlaygroundFeatureSchemaVariantToJSON(value?: PlaygroundFeatureSchemaVariant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'enabled': value.enabled,
        'payload': PlaygroundFeatureSchemaVariantPayloadToJSON(value.payload),
    };
}

