/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProjectSchema,
    ProjectSchemaFromJSON,
    ProjectSchemaFromJSONTyped,
    ProjectSchemaToJSON,
} from './ProjectSchema';

/**
 * 
 * @export
 * @interface ProjectsSchema
 */
export interface ProjectsSchema {
    /**
     * 
     * @type {number}
     * @memberof ProjectsSchema
     */
    version: number;
    /**
     * 
     * @type {Array<ProjectSchema>}
     * @memberof ProjectsSchema
     */
    projects: Array<ProjectSchema>;
}

export function ProjectsSchemaFromJSON(json: any): ProjectsSchema {
    return ProjectsSchemaFromJSONTyped(json, false);
}

export function ProjectsSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': json['version'],
        'projects': ((json['projects'] as Array<any>).map(ProjectSchemaFromJSON)),
    };
}

export function ProjectsSchemaToJSON(value?: ProjectsSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'projects': ((value.projects as Array<any>).map(ProjectSchemaToJSON)),
    };
}

