/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.12.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectEnvironmentSchema
 */
export interface ProjectEnvironmentSchema {
    /**
     * 
     * @type {string}
     * @memberof ProjectEnvironmentSchema
     */
    environment: string;
}

export function ProjectEnvironmentSchemaFromJSON(json: any): ProjectEnvironmentSchema {
    return ProjectEnvironmentSchemaFromJSONTyped(json, false);
}

export function ProjectEnvironmentSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectEnvironmentSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'environment': json['environment'],
    };
}

export function ProjectEnvironmentSchemaToJSON(value?: ProjectEnvironmentSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'environment': value.environment,
    };
}

