/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFeatureSchema
 */
export interface UpdateFeatureSchema {
    /**
     * 
     * @type {string}
     * @memberof UpdateFeatureSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFeatureSchema
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFeatureSchema
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFeatureSchema
     */
    stale?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFeatureSchema
     */
    archived?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFeatureSchema
     */
    createdAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateFeatureSchema
     */
    impressionData?: boolean;
}

export function UpdateFeatureSchemaFromJSON(json: any): UpdateFeatureSchema {
    return UpdateFeatureSchemaFromJSONTyped(json, false);
}

export function UpdateFeatureSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFeatureSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'stale': !exists(json, 'stale') ? undefined : json['stale'],
        'archived': !exists(json, 'archived') ? undefined : json['archived'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'impressionData': !exists(json, 'impressionData') ? undefined : json['impressionData'],
    };
}

export function UpdateFeatureSchemaToJSON(value?: UpdateFeatureSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'type': value.type,
        'stale': value.stale,
        'archived': value.archived,
        'createdAt': value.createdAt,
        'impressionData': value.impressionData,
    };
}

