# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn run test
  capture_vercel_preview_url:
    name: Capture Vercel preview URL
    runs-on: "ubuntu-latest"
    steps:
      - uses: aaimio/vercel-preview-url-action@v1
        id: vercel_preview_url
  cypress-run-e2e:
    runs-on: ubuntu-20.04
    steps:
      - name: Cypress run with env
        uses: cypress-io/github-action@v2
        with:
          env: AUTH_TOKEN=${{ secrets.UNLEASH_TOKEN }}
          config: baseUrl=${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
    
  

