# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn run test
  e2e:
    name: Capture Vercel preview URL
    runs-on: "ubuntu-latest"
    steps:
      - run: sleep 30
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.0.0
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: 'unleash-team'
          vercel_project_id: 'unleash-frontend'
      - name: Cypress run with env
        uses: cypress-io/github-action@v2
        with:
          env: AUTH_TOKEN=${{ secrets.UNLEASH_TOKEN }}
          config: baseUrl=${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
    
  

